name: CI
on:
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build APK 
        run: ./gradlew assembleDebug

      - name: Upload apk
      - uses: actions/upload-artifact@master
        with:
          name: uploading apk
          path: public/
 
